/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mypackage;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {



    @Test(enabled = false)
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void calcRes() {
        double viruchka = 123123.99;
        double course = 3183.40;
        double res = 38.89;

        System.out.println(viruchka/(res*1000));
    }
}
